// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-jTeUB4N7yW40Ecbmz3BBKWG83hocfKY',
    appId: '1:839521872245:web:d6ac530ab703250e9c0b3c',
    messagingSenderId: '839521872245',
    projectId: 'flutter-ojt-adc11',
    authDomain: 'flutter-ojt-adc11.firebaseapp.com',
    storageBucket: 'flutter-ojt-adc11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY9MaKf8kM7usIwmg5E1Lher_FensSVws',
    appId: '1:839521872245:android:af4091ade7951a829c0b3c',
    messagingSenderId: '839521872245',
    projectId: 'flutter-ojt-adc11',
    storageBucket: 'flutter-ojt-adc11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd95TIVdxTuXckJgQEDbDlEWGipbem2DI',
    appId: '1:839521872245:ios:f5cc9130bce199289c0b3c',
    messagingSenderId: '839521872245',
    projectId: 'flutter-ojt-adc11',
    storageBucket: 'flutter-ojt-adc11.firebasestorage.app',
    iosBundleId: 'com.example.ojtProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd95TIVdxTuXckJgQEDbDlEWGipbem2DI',
    appId: '1:839521872245:ios:f5cc9130bce199289c0b3c',
    messagingSenderId: '839521872245',
    projectId: 'flutter-ojt-adc11',
    storageBucket: 'flutter-ojt-adc11.firebasestorage.app',
    iosBundleId: 'com.example.ojtProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-jTeUB4N7yW40Ecbmz3BBKWG83hocfKY',
    appId: '1:839521872245:web:3b71197a5ee698709c0b3c',
    messagingSenderId: '839521872245',
    projectId: 'flutter-ojt-adc11',
    authDomain: 'flutter-ojt-adc11.firebaseapp.com',
    storageBucket: 'flutter-ojt-adc11.firebasestorage.app',
  );
}
